language: python
#
#os: linux
#language: python
#python:
#      - 2.7
#      - 3.4
#      - 3.5
#      - 3.6
#env:
#  - MPI=1
#  - MPI=


matrix:
    include:
        - os: osx
          language: generic
          env: PYTHON=2.7.14
        - os: osx
          language: generic
          env: PYTHON=3.4.6
        - os: osx
          language: generic
          env: PYTHON=3.5.6
        - os: osx
          language: generic
          env: PYTHON=3.6.3

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv virtualenv venv
    source venv/bin/activate
  fi
    

install:
    - python --version
    - mkdir external
    - cd external

    # MPI installation
    - if [ "$MPI" ];
      then
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
          then 
              brew install open-mpi;
          else
              sudo apt-get install openmpi-bin libopenmpi-dev;
          fi;
          pip install mpi4py;
      fi

    # PolyChord install
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
      then 
          brew install gfortran;
      else
          sudo apt-get install gfortran;
      fi;
    - git clone https://github.com/PolyChord/PolyChordLite PolyChord
    - cd PolyChord
    - make MPI=$MPI pypolychord
    - if [ "$MPI" ];
      then
          CC=mpicc CXX=mpicxx python setup.py install;
      else
          python setup.py install;
      fi
    - cd ..

    # MultiNest install
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
      then 
          brew install gfortran lapack blas;
      else
          sudo apt-get install gfortran libblas3 liblapack3;
      fi
    - git clone https://github.com/JohannesBuchner/MultiNest MultiNest
    - cd MultiNest/build
    - cmake ..
    - make
    - cd ../../
    - export LD_LIBRARY_PATH=$PWD/MultiNest/lib/:${LD_LIBRARY_PATH} 

    # PyMultiNest install
    - git clone https://github.com/williamjameshandley/PyMultiNest PyMultiNest
    - cd PyMultiNest
    - python setup.py install
    - cd ..

    # requirements install
    - cd ..
    - pip install -r requirements.txt
    - pip install pytest pytest-cov codecov

script:
    - if [ "$MPI" ];
      then
          mpirun -np 2 python -m pytest tests;
      else
          python -m pytest tests --cov=pybambi;
      fi

after_success:
    - codecov
